version: 1

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  file:
    class: logging.FileHandler
    filename: debug.log
    encoding: utf-8
    formatter: basic

formatters:
  basic:
    style: "{"
    format: "{asctime:s}:{levelname:s}:{name:s}:{funcName:s}:{message:s}"
    #format: "{asctime:s}:{levelname:s}:{filename:s}:{lineno:d}:{message:s}"
    #format: "{asctime:s}:{levelname:s}:{pathname:s}:{lineno:d}:{message:s}"

loggers:
  choreography:
    #handlers: [console, file]
    handlers: [file]
    level: INFO
  choreography.launcher_plugins:
    handlers: [file]
    level: INFO
  asyncio:
    handlers: [file]
    level: WARN
  hbmqtt:
    handlers: [file]
    level: INFO
  __main__:
    handlers: [console, file]
    level: DEBUG
